POST http://localhost:8888/api/v1/auth/login
Content-Type: application/json

{
  "email": "loli@pod.fr",
  "password": "securePass123"
}

<> 2026-04-26T112801.200.json
<> 2026-04-26T111136.200.json
<> 2026-04-26T110533.200.json
<> 2026-04-26T110153.200.json
<> 2026-04-26T105447.200.json
<> 2026-04-19T162521.200.json




###

POST http://localhost:8888/api/v1/auth/register
Content-Type: application/json

{
  "name":"kati" ,
  "email": "loli@pod.fr",
  "password": "securePass123"
}

<> 2026-04-26T112754.201.json
<> 2026-04-26T111105.201.json
<> 2026-04-26T110501.201.json
<> 2026-04-26T103153.201.json
<> 2026-04-26T103110.201.json
<> 2026-04-26T103021.201.json
<> 2026-04-19T162514.201.json

###

GET http://localhost:8888/api/v1/posts/1

<> 2026-04-19T162609.200.json

###

POST http://localhost:8888/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6b29ta0B3ZWIuZnIiLCJpYXQiOjE3NzY2MDg3MjEsImV4cCI6MTc3NjY5NTEyMX0.tq2sIeeVUEUcTQZFKf09MuAo7bFqzuGQkWcNUsLzs78

{
  "title": "WACT&",
  "content": "SPEKER AND AUDIO",
  "category": "PUBLISHED"
}

<> 2026-04-19T162545.201.json
<> 2026-04-19T160214.201.json
<> 2026-04-19T160203.400.json

###

GET http://localhost:8888/api/v1/posts/search?authorId=2&category=DRAFT

###

GET http://localhost:8888/api/v1/posts/category?category=DRAFT

###

GET http://localhost:8888/api/v1/posts/category?category=PUBLISHED

###

PUT http://localhost:8888/api/v1/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6b29ta0B3ZWIuZnIiLCJpYXQiOjE3NzY2MDYwMDEsImV4cCI6MTc3NjY5MjQwMX0._AxqymlgIdGjfGvmSO289Z1GqNdemH10xCQhZaAeUiQ

{
  "id": 1,
  "title": "comunication details",
  "content": "all infos for them",
  "category": "PUBLISHED"
}

###

DELETE http://localhost:8888/api/v1/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6b29ta0B3ZWIuZnIiLCJpYXQiOjE3NzY2MDg3MjEsImV4cCI6MTc3NjY5NTEyMX0.tq2sIeeVUEUcTQZFKf09MuAo7bFqzuGQkWcNUsLzs78

{
  "id": 1,
  "title": "comunication details",
  "content": "all infos for them",
  "category": "PUBLISHED"
}

<> 2026-04-19T162624.400.json
<> 2026-04-19T160246.500.json


###
GET http://localhost:8888/ap1/v1/user/2

###





GET http://localhost:8888/api/v1/user/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2xpQHBvZC5mciIsImlhdCI6MTc3NzE5NTY4MSwiZXhwIjoxNzc3MjgyMDgxfQ.KM4Y8dakBjDMrks8tFA0zYLUM7n5Beoi1LoJe5nEaUM

<> 2026-04-26T112844.200.json
<> 2026-04-26T105640.200.json
<> 2026-04-26T105629.200.json
<> 2026-04-26T105617.200.json
<> 2026-04-26T105603.200.json

###

GET http://localhost:8888/api/v1/user/email/loli@pod.fr
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2xpQHBvZC5mciIsImlhdCI6MTc3NzE5NTY4MSwiZXhwIjoxNzc3MjgyMDgxfQ.KM4Y8dakBjDMrks8tFA0zYLUM7n5Beoi1LoJe5nEaUM

<> f-2.txt
<> f-1.txt
<> f.txt

###

PUT http://localhost:8888/api/v1/user/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb3VAYW9sLmZyIiwiaWF0IjoxNzc3MTkzNjg3LCJleHAiOjE3NzcyODAwODd9.A0SI4C0x7cvMlAEgw6XxE8IRVKn__97B1GJBPxviZ2c

{
  "name":"lulu" ,
  "email": "rot@aol.fr"
}

<> 2026-04-26T110054.200.json

###

DELETE http://localhost:8888/api/v1/user/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2xpQHBvZC5mciIsImlhdCI6MTc3NzE5NTY4MSwiZXhwIjoxNzc3MjgyMDgxfQ.KM4Y8dakBjDMrks8tFA0zYLUM7n5Beoi1LoJe5nEaUM
###

