spring:
  application:
    name: blog_app
  profiles:
    default: dev
  config:
    import: optional:file:.env[.properties]

# Logging
logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss}- %msg%n'

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: ${spring.application.name}



